### ISSUE TITLE
Techniques to retaining selections after refreshing

### ISSUE THREAD

**Issue by bryanveloso** [joshaber/JAListView#8]
I'm using `JASectionedListView` in a sort of "master/detail" way and I'm struggling to come up with ways to retain the selection after a refresh (which is triggered manually or at a set interval).

![2014-02-28 at 12 00 pm](https://f.cloud.github.com/assets/1258/2297841/0c7cadfe-a0b3-11e3-9225-4268ff0308a0.png)

**Comment by joshaber** [comment]
Disclaimer: it's been a _super_ long time since I've poked around `JAListView`.

Could you do something like:

``` objc
NSArray *selectedViews = self.listView.selectedViews;
[self.listView reloadData];
for (JAListViewItem *view in selectedViews) {
    [self.listView selectView:view];
}
```

**Comment by bryanveloso** [comment]
That seems to work. The logs say that the view is selected, but for some reason the state isn't being toggled. Time to debug that.

:crying_cat_face:

**Comment by bryanveloso** [comment]
Seems like `drawRect:` isn't getting called, but that might be due to my use of RAC.

**Comment by bryanveloso** [comment]
@joshaber: Yeah, I'm not sure what's going on here. I only get the desired effect when I `-mouseDown` on an item, any attempt to try and set the `selected` attribute programmatically will set the attribute, but it will not redraw the cell, despite the values (label colors, etc) being correctly set.

Stepping through everything, it seems like the cell IS redrawn... but the whole thing is overridden when the reload finishes. I'm really not sure why `-mouseDown` would work and this wouldn't despite doing essentially the same thing.

**Comment by joshaber** [comment]
Any chance the reload + restoration is being done on something other than the main thread?

**Comment by bryanveloso** [comment]
This is my current RACSignal for refreshing the list. I've tried tacking on `deliverOn` with no luck, but I could be using that wrong.

``` objc
[[RACSignal
    combineLatest:@[RACObserve(self, viewModel.authenticatedStreams), RACObserve(self, viewModel.featuredStreams)]]
    subscribeNext:^(id x) {
        @strongify(self);
        NSSet *selectedViews = [NSSet setWithArray:_listView.selectedViews];
        [_listView reloadData];
        for (StreamListItemView *item in selectedViews) {
            [_listView selectView:item];
        }
    } error:^(NSError *error) {
        @strongify(self);
        DDLogError(@"Application (%@): (Error) %@", [self class], error);
    }];
```

I tried a `dispatch` thing as well, which didn't work either. :< But I don't totally know what I'm doing.

``` objc
double delayInSeconds = 0.1;
dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, delayInSeconds * NSEC_PER_SEC);
dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
    NSSet *selectedViews = [NSSet setWithArray:_listView.selectedViews];
    [_listView reloadData];
    for (StreamListItemView *item in selectedViews) {
        [_listView selectView:item];
    }
});
```

**Comment by joshaber** [comment]
Hrm, so, looking at the code it's hard to know how any of this ever worked.

![](http://www.reactiongifs.com/wp-content/uploads/2012/10/shame.gif)

It _seems_ to throw away the old views and create new views each time `-reloadData` is called. So the old view might still exist, but it isn't anyone's subview so it isn't drawn. There's no great way around this. I seem to recall that [`JAObjectListView`](https://github.com/joshaber/JAListView/blob/master/JAObjectListView.h) kinda filled this void by making it  easy to replace specific views.

**Comment by bryanveloso** [comment]
I'll take a look at that then. Thanks for spending some time to look into it for me! :cookie:

**Comment by bryanveloso** [comment]
That did it! It took a little bit to get my `JASectionedListView` to work with `JAObjectListView` (and RAC). But it works with `-viewItemForObject:`!

:metal:
