### ISSUE TITLE
Programmatically set the selection state is not working 

### ISSUE THREAD

**Issue by mammaiap** [joshaber/JAListView#9]
i tried to set the selected state for the view after reloaddata.but it is not redrawn... but mouse down is working correctly...

below is the code in JAListView .... the selected item is not redrawn to show as selected state..

-(void)refreshAllViewsandRetainSelection
{
    NSArray *selectedViews = self.selectedViews;
    [self reloadData];
    for (JAListViewItem *view in selectedViews) 
    {
        [self selectView:view];
    }
}

how to fix this problem?

Thanks,
Muthu

**Comment by joshaber** [comment]
This sounds like the same problem as https://github.com/joshaber/JAListView/issues/8. Check that out and let me know if it doesn't answer your question.
